# Generated by Django 2.2.6 on 2019-12-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0003_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
